name: Central Client Load Test

on:
  workflow_dispatch:
    inputs:
      instance_count:
        description: Count of instances to be used for load testing
        required: true
        default: 1
      iterations:
        description: How many iterations to be run
        required: true
        default: 1
      interval:
        description: Interval time between each iteration
        required: true
        default: 600
      output_folder_prefix:
        description: Prefix for the output folder
        required: true
        default: "okhttp3_r0_c600"

jobs:
  ubuntu_build:
    name: Build with tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: prj_api_u35TimeOut

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup Speedtest
        run: pip install speedtest-cli


      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          NUM_INSTANCES: ${{ inputs.instance_count }}
          NUM_ITERATIONS: ${{ inputs.iterations }}
          INTERVAL: ${{ inputs.interval }}
          PREFIX: ${{ inputs.output_folder_prefix }}
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew clean build -x test -x check --scan --no-daemon 
          ./pull_script/bal_pull.sh

      - name: Commit files
        run: |
          git config --global user.name 'Luheerathan Thevakumar'
          git config --global user.email 'Luhee27@gmail.com'
          git add pull_script/OLD_OP/*
          git commit -am "[Add output]"
          git push origin prj_api_u35TimeOut